apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    enabled: true
    samplingRate: "1"
    includeBody: true
    zipkin:
      endpointAddress: http://zipkin:9411/api/v2/spans
